### PR TITLE
Check BWC license before starting the install

### LINKED ISSUE #28: Check BWC License validity as early step
```
########################################################
       Installing BWC Enterprise unstable       
########################################################
########################################################
                 Using Unstable Repos
########################################################

    No access to enterprise repo 
    LICENSE: ... not valid.
  
```

I think it makes sense to verify BWC license validity before installing entire StackStorm Community version.
Installing StackStorm and all dependencies takes time and it might be annoying and counter-intuitive that after configuring almost everything script may hang with error, saying that license is not valid.

### PR DESCRIPTION
**Pull request by armab**
Fixes #28

Verify BWC license validity as early step before starting entire StackStorm Community installation.

```
./bwc-installer.sh --license=123

      LICENSE: 123 not valid.

      Please contact support@brocade.com. Please include the SKU and the invalid license key in the email.
```

### CODE REVIEW

**Comment by armab** [comment]
@warrenvw Please take a look 👀 as well

**Comment by warrenvw** [comment]
👍 LGTM.

**Comment by warrenvw** [comment]
Looks like I lack the permissions to add myself as a reviewer to approve this PR.

**Comment by LindsayHill** [comment]
@warrenvw you should now have permissions for this repo

**Comment by armab** [comment]
OK, this is deployed to production.

**Pull request merged**
