### PR TITLE
Push yum update

### PR DESCRIPTION
**Pull request by rmadapur**
Invoking yum update before installation of packages

### CODE REVIEW

**Comment by LindsayHill** [comment]
I think it's a bad idea to do a blind update of all system packages, with no warning for the user. 

@samirsss is there a specific reason for doing this? 

Are there specific packages that need to be updated, or are we just doing this because we hope it will fix something? Why are we only doing it for RHEL systems? What about Ubuntu? And why do we only do it for DC Fabric installations? What about ST2 or BWC users?

**Comment by LindsayHill** [comment]
Also, if this is required, where is the matching PR for the ipfabric-docs manual installation instructions? https://github.com/StackStorm/ipfabric-docs/blob/master/docs/source/solutions/dcfabric/install.rst

**Comment by lakshmi-kannan** [comment]
@rmadapur Who approved this PR? We have a rule nothing should be merged without an explicit approval. I see

>rmadapur requested a review from samirsss 2 days ago

But no audit log on who approved it. 

This PR doesn't have a proper description. It doesn't say 1. Why this change is needed? 2. Logs to show before this change, installation is broken. 3. Logs to show after this change, installation works because blah blah blah.

**Comment by lakshmi-kannan** [comment]
I made the repo so that without a review no one can merge things anymore. https://github.com/StackStorm/bwc-installer/settings/branches/master

**Comment by rmadapur** [comment]
https://stackstorm.atlassian.net/browse/CANDY-638

**Comment by rmadapur** [comment]
The dependencies in the dcfabric-suite was not getting upgraded. 
The other option is to explicitly install the dependencies
 yum deplist dcfabric-suite | awk '/provider:/ {print $2}' |  xargs yum -y install

**Comment by rmadapur** [comment]
Without yum-update 
===============
yum install dcfabric-suite - 1.2
Loaded plugins: fastestmirror
You need to be root to perform this command.
[vagrant@win7test ~]$ sudo yum install dcfabric-suite - 1.2
Loaded plugins: fastestmirror
StackStorm_enterprise/x86_64/signature                                                                                                        |  836 B  00:00:00
StackStorm_enterprise/x86_64/signature                                                                                                        | 1.0 kB  00:00:00 !!!
StackStorm_enterprise-source/signature                                                                                                        |  836 B  00:00:00
StackStorm_enterprise-source/signature                                                                                                        |  951 B  00:00:00 !!!
StackStorm_stable/x86_64/signature                                                                                                            |  836 B  00:00:00
StackStorm_stable/x86_64/signature                                                                                                            | 1.0 kB  00:00:00 !!!
StackStorm_stable-source/signature                                                                                                            |  836 B  00:00:00
StackStorm_stable-source/signature                                                                                                            |  951 B  00:00:00 !!!
StackStorm_staging-enterprise/x86_64/signature                                                                                                |  836 B  00:00:00
StackStorm_staging-enterprise/x86_64/signature                                                                                                | 1.0 kB  00:00:00 !!!
StackStorm_staging-enterprise-source/signature                                                                                                |  836 B  00:00:00
StackStorm_staging-enterprise-source/signature                                                                                                |  951 B  00:00:00 !!!
Loading mirror speeds from cached hostfile
 * base: mirror.cc.columbia.edu
 * epel: mirror.cogentco.com
 * extras: mirrors.usc.edu
 * updates: repos-va.psychz.net
No package 1.2 available.
Resolving Dependencies
--> Running transaction check
---> Package dcfabric-suite.x86_64 0:1.1-2 will be updated
---> Package dcfabric-suite.x86_64 0:1.2-3 will be an update
--> Processing Dependency: dcfabric-packs >= 1.2 for package: dcfabric-suite-1.2-3.x86_64
--> Running transaction check
---> Package dcfabric-packs.x86_64 0:1.1-1 will be updated
---> Package dcfabric-packs.x86_64 0:1.2-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================================================
 Package                                 Arch                            Version                        Repository                                              Size
=====================================================================================================================================================================
Updating:
 dcfabric-suite                          x86_64                          1.2-3                          StackStorm_staging-enterprise                           41 k
Updating for dependencies:
 dcfabric-packs                          x86_64                          1.2-1                          StackStorm_staging-enterprise                           75 k

Transaction Summary
=====================================================================================================================================================================
Upgrade  1 Package (+1 Dependent package)

Total download size: 116 
*****************************************************************************
All the dependencies in the package dc-fabric-suite were not getting upgraded


After the "yum update" all the dependecies of the package were getting upgraded

**Comment by LindsayHill** [comment]
@rmadapur 
> The dependencies in the dcfabric-suite was not getting upgraded.

Which dependencies were not getting upgraded? This looks like maybe there's a packaging issue, where `dc-fabric-suite` is declaring a dependency without specifying a minimum version?

**Comment by samirsss** [comment]
Lets revert this PR and have the right dependencies only getting updated/upgraded. I think its just bwc-cli, dcfabric-packs and bwc-topology that we can update here.

Seems like we might break other things if we do a blanket update here.

**Comment by LindsayHill** [comment]
Installed a new CentOS7 BWC + DC Fabric system using latest `stable`.

```sh
vagrant@bwcvagrantel7 ~]$ yum list dcfabric-suite
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.kernel.org
 * epel: mirror.sjc02.svwh.net
 * extras: mirrors.kernel.org
 * updates: mirrors.usc.edu
Installed Packages
dcfabric-suite.x86_64                                           1.1-2                                           @StackStorm_enterprise
[vagrant@bwcvagrantel7 ~]$ yum deplist dcfabric-suite
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.kernel.org
 * epel: mirror.sjc02.svwh.net
 * extras: mirrors.kernel.org
 * updates: mirrors.usc.edu
package: dcfabric-suite.x86_64 1.1-2
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-21.el7_3
  dependency: bwc-cli >= 1.1
   provider: bwc-cli.x86_64 1.1-1
  dependency: bwc-topology >= 1.1
   provider: bwc-topology.x86_64 1.1-2
  dependency: dcfabric-packs >= 1.1
   provider: dcfabric-packs.x86_64 1.1-1
[vagrant@bwcvagrantel7 ~]$
```

Those version mappings look pretty good. 

I **think** that maybe the actual initial problem here was related to upgrading DC Fabric Suite using the installer script, to upgrade to a TP release? Is that right? Maybe the dependency mapping in the TP packaging is not right?

**Comment by samirsss** [comment]
@LindsayHill the issue was during an upgrade from 1.1 to 1.2 TP packages.

**Comment by LindsayHill** [comment]
If it is an upgrade issue, then on that note, looks like we may need to think through that update procedure. Updates for ST2/BWC are *not* done using the install script - we recommend using `yum`/`apt`: https://docs.stackstorm.com/install/upgrades.html

**Comment by LindsayHill** [comment]
@samirsss so yeah. This shouldn't be in that script at all. Upgrades should be done with `sudo yum update dcfabric-suite`, and that package should be properly declaring its dependencies. 

Check the RPM packaging for it, and check what it has as dependencies. My guess is that it still only needed v1.1 of those other packages, not some newer version (1.2 or whatever you're calling it)

**Comment by samirsss** [comment]
@LindsayHill agreed that this needs to be looked at. I assume @rmadapur can pick it up.

**Comment by rmadapur** [comment]
I will create a PR to revert yum update

**Pull request merged**
